// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_OC_wNjcHkQyhj9gizo-kU8t68qLyIRs',
    appId: '1:510594999137:android:e996d86932b6dd55551b20',
    messagingSenderId: '510594999137',
    projectId: 'my-vest-project',
    storageBucket: 'my-vest-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmmq0bRzo3fQm0U8Vr9B38s0kfn72SwT0',
    appId: '1:510594999137:ios:a4210f71099bcb56551b20',
    messagingSenderId: '510594999137',
    projectId: 'my-vest-project',
    storageBucket: 'my-vest-project.appspot.com',
    androidClientId:
        '510594999137-05veerpni9tkmke6nijlmajfhub0atfl.apps.googleusercontent.com',
    iosClientId:
        '510594999137-pkkuncr21taho7c7bd6j70oa13h5n8bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetsProject',
  );
}
