name: vets_project
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  ##### State MAnagement #####
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  get_it: ^7.2.0

  ##### Lib #####
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  permission_handler: ^10.0.0
  auto_route: ^4.2.1
  cached_network_image: ^3.2.1
  flutter_parsed_text: ^2.2.1
  url_launcher: ^6.1.5
  intl: ^0.17.0
  video_player: ^2.4.7
  slide_countdown: ^0.3.3
  #flutter_webrtc: ^0.9.3

  ##### Tools #####
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.3
  firebase_messaging: ^13.0.0

  ##### Widgets #####
  easy_rich_text: ^1.1.0
  auto_size_text: ^3.0.0
  checkbox_formfield: ^0.2.0
  dropdown_textfield: ^1.0.3
  flutter_switch: ^0.3.2
  getwidget: ^3.0.1
  flutter_spinkit: ^5.1.0
  easy_splash_screen: ^1.0.4
  dash_chat_2: ^0.0.14
  bubble: ^1.2.1
  photo_view: ^0.14.0
  photo_gallery: ^1.1.1
  transparent_image: ^2.0.0
  voice_message_package: ^0.0.74

  #### Data Base #####
  firebase_core: ^1.20.1
  firebase_storage: ^10.3.5
  firebase_auth: ^3.6.3
  cloud_firestore: ^3.4.4
  image_picker: ^0.8.5+3
  uuid: ^3.0.6
  path_provider: ^2.0.11
  audio_waveforms: 0.1.4
  location: ^4.4.0
  flutter_sound: ^9.2.13
  just_audio: ^0.9.28
  file_picker: ^3.0.4
  video_thumbnail: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  ##### Test #####
  mockito: ^5.3.0
  fake_cloud_firestore: ^1.3.1
  firebase_storage_mocks: ^0.5.1
  firebase_auth_mocks: ^0.8.5+1
  auto_route_generator: any
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
